//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Sources/Input/Player Input.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Game.Inputs
{
    public partial class @PlayerInput: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @PlayerInput()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""Player Input"",
    ""maps"": [
        {
            ""name"": ""UserAction"",
            ""id"": ""34c919f5-509b-4359-bcd5-b408c30749cb"",
            ""actions"": [
                {
                    ""name"": ""StopPlaying"",
                    ""type"": ""Button"",
                    ""id"": ""52be360f-49cd-42fa-ac9b-032da0e60b59"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action"",
                    ""type"": ""Button"",
                    ""id"": ""35b81cef-dc92-4ca0-b16d-3bfcae1628f2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenInventary"",
                    ""type"": ""Button"",
                    ""id"": ""994f769c-29f5-4992-8663-e6069fef81ab"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""dff7c946-71c2-4156-b8b6-bf3e390b21bf"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StopPlaying"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""29d3f617-04fa-422b-b482-5245345bbd68"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4b51a62c-b73d-4028-9adf-e06d0ecabd6a"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenInventary"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Movements"",
            ""id"": ""036ecd8c-e4ec-4241-9888-d84c12431973"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""PassThrough"",
                    ""id"": ""dbd93496-9b54-4da7-bb91-ce70bdb7092f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""PassThrough"",
                    ""id"": ""954e5394-a976-4977-a31c-d43d21540ca4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jumpe"",
                    ""type"": ""Button"",
                    ""id"": ""c89c3ccd-7f07-4911-8730-217395eee00b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SitDown"",
                    ""type"": ""Button"",
                    ""id"": ""2b34dc66-fa0f-4240-a79b-fa7d679dedfc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Accalerate"",
                    ""type"": ""Button"",
                    ""id"": ""918eba05-dd3e-4b14-908c-c6c96bcf05cd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""277e3b85-29ec-4674-a796-e2b7a8957505"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""1afd9d2c-0547-4c8f-a4f4-76a2acb5258f"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""0bdea74a-b4b9-4890-bffa-da684e2e973f"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""447c5dac-9d86-4dbd-bbec-c8b1a7f7386a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""da4a9a5d-e56e-4598-902d-321fbc643677"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d7642e73-8b3c-4e9a-a426-c0ffcad347d0"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c7b7c98-e146-4a0a-b791-7089cb6e59a3"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jumpe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""695d79c8-1e12-4e0e-afa2-6074152d7bd8"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jumpe"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""5e922530-1c06-4b73-bdef-576debc4b765"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jumpe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""412a9863-a59b-4095-ad54-572330eb2513"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jumpe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""a6e72a9e-14f3-4207-80c1-7cee07f4688f"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jumpe"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""80c80694-a02a-410f-864c-6e3870880fec"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jumpe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""b8ac8e99-abd7-4dc4-ae5b-3403aecbd046"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jumpe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""c8263631-1887-4196-a635-98d7fb5e4ec8"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jumpe"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""e44a96ff-cd6a-4969-a293-104537cbd2da"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jumpe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""0f1e468d-17c7-459b-9d50-d70ef6686811"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jumpe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""430df9d8-f2ef-49fd-bc9b-7caa7e68658a"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jumpe"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""7c51014a-5b6b-4176-b19a-4e99bd06c632"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jumpe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""388bc075-b95f-41f6-9dce-ed46336c039c"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jumpe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d974db72-6727-4064-9735-630efdfd555d"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SitDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""db7f9830-d84d-42dc-8032-e678fb636951"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Accalerate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""5281fd4c-156e-45f3-86eb-cc31faf76a63"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Accalerate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""f8d339bc-0c1e-4b87-a85b-18cb703b6f46"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Accalerate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""Gun"",
            ""id"": ""1c314dc1-6062-4f12-b61d-6eb7b9d3a4e7"",
            ""actions"": [
                {
                    ""name"": ""GetTheNinthWeapon"",
                    ""type"": ""Value"",
                    ""id"": ""a8890f54-68b4-46b3-bf5d-e4047f352348"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""GetTheEghthWeapon"",
                    ""type"": ""Value"",
                    ""id"": ""80ab6b7e-ca71-48e1-8208-cca4f594408a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""GetTheSeventhWeapon"",
                    ""type"": ""Value"",
                    ""id"": ""1d38a36e-7a89-44a9-8cf9-5118758b85a8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""GetTheSixthWeapon"",
                    ""type"": ""Value"",
                    ""id"": ""76b48e45-39c4-4b88-97ea-d426315aeb42"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""GetTheFifthWeapon"",
                    ""type"": ""Value"",
                    ""id"": ""c24538e2-9e66-49ee-8004-6db266fdd282"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""GetTheFourthWeapon"",
                    ""type"": ""Value"",
                    ""id"": ""aac0a10f-ac45-4d60-aa4c-cb7cd4e19b4b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""GetTheThirdWeapon"",
                    ""type"": ""Value"",
                    ""id"": ""7856a734-f945-4f8c-879f-1f8ecf656d94"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""GetASecondWeapon"",
                    ""type"": ""Value"",
                    ""id"": ""d19f9b21-639b-4ea2-aade-fa6357666aaa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""GetAFirstWeapon "",
                    ""type"": ""Value"",
                    ""id"": ""d9d6dbca-859a-4d1a-8a09-a1ef80242202"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Shot"",
                    ""type"": ""Button"",
                    ""id"": ""aba73e4a-94d5-4cc6-bcad-5978e7b54da6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reload"",
                    ""type"": ""Button"",
                    ""id"": ""9715e145-8d43-46c6-b5b8-4b6b66a0e6bb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TakeAim"",
                    ""type"": ""Button"",
                    ""id"": ""ee4e0dab-982a-4c34-b05c-fa97febc55b7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a6b52907-3fab-4ed8-b197-c5a2a74712d8"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2302ea06-560b-4cca-b5a1-967b1a3bf0d0"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": ""Scale"",
                    ""groups"": """",
                    ""action"": ""GetASecondWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""69b783b9-2d62-482f-9cd7-9987dbdbb218"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=2)"",
                    ""groups"": """",
                    ""action"": ""GetTheThirdWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab12fcf3-5ec0-46e2-8e48-c5e94b7c43ff"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=3)"",
                    ""groups"": """",
                    ""action"": ""GetTheFourthWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a3d2691-26d3-4717-b164-bb7f2f6fb8b0"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=5)"",
                    ""groups"": """",
                    ""action"": ""GetTheSixthWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ef3f3fab-ffbd-4bbf-8b38-0d438b11164c"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=6)"",
                    ""groups"": """",
                    ""action"": ""GetTheSeventhWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cbc2a138-1b17-477e-b90d-f7c0dfed1266"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=7)"",
                    ""groups"": """",
                    ""action"": ""GetTheEghthWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d45a67e0-4718-4033-a7be-5dc606fd3632"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=8)"",
                    ""groups"": """",
                    ""action"": ""GetTheNinthWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e441c99c-8b44-41a3-93ac-c31576df2a7f"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""10df861c-7178-4f8b-b038-c7747ebb6ca9"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TakeAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bc3e4fbb-a138-48bc-8303-c12cbcc05946"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=4)"",
                    ""groups"": """",
                    ""action"": ""GetTheFifthWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f768b63c-1f1f-4554-8e79-db045858e320"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=0)"",
                    ""groups"": """",
                    ""action"": ""GetAFirstWeapon "",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // UserAction
            m_UserAction = asset.FindActionMap("UserAction", throwIfNotFound: true);
            m_UserAction_StopPlaying = m_UserAction.FindAction("StopPlaying", throwIfNotFound: true);
            m_UserAction_Action = m_UserAction.FindAction("Action", throwIfNotFound: true);
            m_UserAction_OpenInventary = m_UserAction.FindAction("OpenInventary", throwIfNotFound: true);
            // Movements
            m_Movements = asset.FindActionMap("Movements", throwIfNotFound: true);
            m_Movements_Move = m_Movements.FindAction("Move", throwIfNotFound: true);
            m_Movements_Rotate = m_Movements.FindAction("Rotate", throwIfNotFound: true);
            m_Movements_Jumpe = m_Movements.FindAction("Jumpe", throwIfNotFound: true);
            m_Movements_SitDown = m_Movements.FindAction("SitDown", throwIfNotFound: true);
            m_Movements_Accalerate = m_Movements.FindAction("Accalerate", throwIfNotFound: true);
            // Gun
            m_Gun = asset.FindActionMap("Gun", throwIfNotFound: true);
            m_Gun_GetTheNinthWeapon = m_Gun.FindAction("GetTheNinthWeapon", throwIfNotFound: true);
            m_Gun_GetTheEghthWeapon = m_Gun.FindAction("GetTheEghthWeapon", throwIfNotFound: true);
            m_Gun_GetTheSeventhWeapon = m_Gun.FindAction("GetTheSeventhWeapon", throwIfNotFound: true);
            m_Gun_GetTheSixthWeapon = m_Gun.FindAction("GetTheSixthWeapon", throwIfNotFound: true);
            m_Gun_GetTheFifthWeapon = m_Gun.FindAction("GetTheFifthWeapon", throwIfNotFound: true);
            m_Gun_GetTheFourthWeapon = m_Gun.FindAction("GetTheFourthWeapon", throwIfNotFound: true);
            m_Gun_GetTheThirdWeapon = m_Gun.FindAction("GetTheThirdWeapon", throwIfNotFound: true);
            m_Gun_GetASecondWeapon = m_Gun.FindAction("GetASecondWeapon", throwIfNotFound: true);
            m_Gun_GetAFirstWeapon = m_Gun.FindAction("GetAFirstWeapon ", throwIfNotFound: true);
            m_Gun_Shot = m_Gun.FindAction("Shot", throwIfNotFound: true);
            m_Gun_Reload = m_Gun.FindAction("Reload", throwIfNotFound: true);
            m_Gun_TakeAim = m_Gun.FindAction("TakeAim", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // UserAction
        private readonly InputActionMap m_UserAction;
        private List<IUserActionActions> m_UserActionActionsCallbackInterfaces = new List<IUserActionActions>();
        private readonly InputAction m_UserAction_StopPlaying;
        private readonly InputAction m_UserAction_Action;
        private readonly InputAction m_UserAction_OpenInventary;
        public struct UserActionActions
        {
            private @PlayerInput m_Wrapper;
            public UserActionActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @StopPlaying => m_Wrapper.m_UserAction_StopPlaying;
            public InputAction @Action => m_Wrapper.m_UserAction_Action;
            public InputAction @OpenInventary => m_Wrapper.m_UserAction_OpenInventary;
            public InputActionMap Get() { return m_Wrapper.m_UserAction; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(UserActionActions set) { return set.Get(); }
            public void AddCallbacks(IUserActionActions instance)
            {
                if (instance == null || m_Wrapper.m_UserActionActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_UserActionActionsCallbackInterfaces.Add(instance);
                @StopPlaying.started += instance.OnStopPlaying;
                @StopPlaying.performed += instance.OnStopPlaying;
                @StopPlaying.canceled += instance.OnStopPlaying;
                @Action.started += instance.OnAction;
                @Action.performed += instance.OnAction;
                @Action.canceled += instance.OnAction;
                @OpenInventary.started += instance.OnOpenInventary;
                @OpenInventary.performed += instance.OnOpenInventary;
                @OpenInventary.canceled += instance.OnOpenInventary;
            }

            private void UnregisterCallbacks(IUserActionActions instance)
            {
                @StopPlaying.started -= instance.OnStopPlaying;
                @StopPlaying.performed -= instance.OnStopPlaying;
                @StopPlaying.canceled -= instance.OnStopPlaying;
                @Action.started -= instance.OnAction;
                @Action.performed -= instance.OnAction;
                @Action.canceled -= instance.OnAction;
                @OpenInventary.started -= instance.OnOpenInventary;
                @OpenInventary.performed -= instance.OnOpenInventary;
                @OpenInventary.canceled -= instance.OnOpenInventary;
            }

            public void RemoveCallbacks(IUserActionActions instance)
            {
                if (m_Wrapper.m_UserActionActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IUserActionActions instance)
            {
                foreach (var item in m_Wrapper.m_UserActionActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_UserActionActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public UserActionActions @UserAction => new UserActionActions(this);

        // Movements
        private readonly InputActionMap m_Movements;
        private List<IMovementsActions> m_MovementsActionsCallbackInterfaces = new List<IMovementsActions>();
        private readonly InputAction m_Movements_Move;
        private readonly InputAction m_Movements_Rotate;
        private readonly InputAction m_Movements_Jumpe;
        private readonly InputAction m_Movements_SitDown;
        private readonly InputAction m_Movements_Accalerate;
        public struct MovementsActions
        {
            private @PlayerInput m_Wrapper;
            public MovementsActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @Move => m_Wrapper.m_Movements_Move;
            public InputAction @Rotate => m_Wrapper.m_Movements_Rotate;
            public InputAction @Jumpe => m_Wrapper.m_Movements_Jumpe;
            public InputAction @SitDown => m_Wrapper.m_Movements_SitDown;
            public InputAction @Accalerate => m_Wrapper.m_Movements_Accalerate;
            public InputActionMap Get() { return m_Wrapper.m_Movements; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(MovementsActions set) { return set.Get(); }
            public void AddCallbacks(IMovementsActions instance)
            {
                if (instance == null || m_Wrapper.m_MovementsActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_MovementsActionsCallbackInterfaces.Add(instance);
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Rotate.started += instance.OnRotate;
                @Rotate.performed += instance.OnRotate;
                @Rotate.canceled += instance.OnRotate;
                @Jumpe.started += instance.OnJumpe;
                @Jumpe.performed += instance.OnJumpe;
                @Jumpe.canceled += instance.OnJumpe;
                @SitDown.started += instance.OnSitDown;
                @SitDown.performed += instance.OnSitDown;
                @SitDown.canceled += instance.OnSitDown;
                @Accalerate.started += instance.OnAccalerate;
                @Accalerate.performed += instance.OnAccalerate;
                @Accalerate.canceled += instance.OnAccalerate;
            }

            private void UnregisterCallbacks(IMovementsActions instance)
            {
                @Move.started -= instance.OnMove;
                @Move.performed -= instance.OnMove;
                @Move.canceled -= instance.OnMove;
                @Rotate.started -= instance.OnRotate;
                @Rotate.performed -= instance.OnRotate;
                @Rotate.canceled -= instance.OnRotate;
                @Jumpe.started -= instance.OnJumpe;
                @Jumpe.performed -= instance.OnJumpe;
                @Jumpe.canceled -= instance.OnJumpe;
                @SitDown.started -= instance.OnSitDown;
                @SitDown.performed -= instance.OnSitDown;
                @SitDown.canceled -= instance.OnSitDown;
                @Accalerate.started -= instance.OnAccalerate;
                @Accalerate.performed -= instance.OnAccalerate;
                @Accalerate.canceled -= instance.OnAccalerate;
            }

            public void RemoveCallbacks(IMovementsActions instance)
            {
                if (m_Wrapper.m_MovementsActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IMovementsActions instance)
            {
                foreach (var item in m_Wrapper.m_MovementsActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_MovementsActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public MovementsActions @Movements => new MovementsActions(this);

        // Gun
        private readonly InputActionMap m_Gun;
        private List<IGunActions> m_GunActionsCallbackInterfaces = new List<IGunActions>();
        private readonly InputAction m_Gun_GetTheNinthWeapon;
        private readonly InputAction m_Gun_GetTheEghthWeapon;
        private readonly InputAction m_Gun_GetTheSeventhWeapon;
        private readonly InputAction m_Gun_GetTheSixthWeapon;
        private readonly InputAction m_Gun_GetTheFifthWeapon;
        private readonly InputAction m_Gun_GetTheFourthWeapon;
        private readonly InputAction m_Gun_GetTheThirdWeapon;
        private readonly InputAction m_Gun_GetASecondWeapon;
        private readonly InputAction m_Gun_GetAFirstWeapon;
        private readonly InputAction m_Gun_Shot;
        private readonly InputAction m_Gun_Reload;
        private readonly InputAction m_Gun_TakeAim;
        public struct GunActions
        {
            private @PlayerInput m_Wrapper;
            public GunActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @GetTheNinthWeapon => m_Wrapper.m_Gun_GetTheNinthWeapon;
            public InputAction @GetTheEghthWeapon => m_Wrapper.m_Gun_GetTheEghthWeapon;
            public InputAction @GetTheSeventhWeapon => m_Wrapper.m_Gun_GetTheSeventhWeapon;
            public InputAction @GetTheSixthWeapon => m_Wrapper.m_Gun_GetTheSixthWeapon;
            public InputAction @GetTheFifthWeapon => m_Wrapper.m_Gun_GetTheFifthWeapon;
            public InputAction @GetTheFourthWeapon => m_Wrapper.m_Gun_GetTheFourthWeapon;
            public InputAction @GetTheThirdWeapon => m_Wrapper.m_Gun_GetTheThirdWeapon;
            public InputAction @GetASecondWeapon => m_Wrapper.m_Gun_GetASecondWeapon;
            public InputAction @GetAFirstWeapon => m_Wrapper.m_Gun_GetAFirstWeapon;
            public InputAction @Shot => m_Wrapper.m_Gun_Shot;
            public InputAction @Reload => m_Wrapper.m_Gun_Reload;
            public InputAction @TakeAim => m_Wrapper.m_Gun_TakeAim;
            public InputActionMap Get() { return m_Wrapper.m_Gun; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(GunActions set) { return set.Get(); }
            public void AddCallbacks(IGunActions instance)
            {
                if (instance == null || m_Wrapper.m_GunActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_GunActionsCallbackInterfaces.Add(instance);
                @GetTheNinthWeapon.started += instance.OnGetTheNinthWeapon;
                @GetTheNinthWeapon.performed += instance.OnGetTheNinthWeapon;
                @GetTheNinthWeapon.canceled += instance.OnGetTheNinthWeapon;
                @GetTheEghthWeapon.started += instance.OnGetTheEghthWeapon;
                @GetTheEghthWeapon.performed += instance.OnGetTheEghthWeapon;
                @GetTheEghthWeapon.canceled += instance.OnGetTheEghthWeapon;
                @GetTheSeventhWeapon.started += instance.OnGetTheSeventhWeapon;
                @GetTheSeventhWeapon.performed += instance.OnGetTheSeventhWeapon;
                @GetTheSeventhWeapon.canceled += instance.OnGetTheSeventhWeapon;
                @GetTheSixthWeapon.started += instance.OnGetTheSixthWeapon;
                @GetTheSixthWeapon.performed += instance.OnGetTheSixthWeapon;
                @GetTheSixthWeapon.canceled += instance.OnGetTheSixthWeapon;
                @GetTheFifthWeapon.started += instance.OnGetTheFifthWeapon;
                @GetTheFifthWeapon.performed += instance.OnGetTheFifthWeapon;
                @GetTheFifthWeapon.canceled += instance.OnGetTheFifthWeapon;
                @GetTheFourthWeapon.started += instance.OnGetTheFourthWeapon;
                @GetTheFourthWeapon.performed += instance.OnGetTheFourthWeapon;
                @GetTheFourthWeapon.canceled += instance.OnGetTheFourthWeapon;
                @GetTheThirdWeapon.started += instance.OnGetTheThirdWeapon;
                @GetTheThirdWeapon.performed += instance.OnGetTheThirdWeapon;
                @GetTheThirdWeapon.canceled += instance.OnGetTheThirdWeapon;
                @GetASecondWeapon.started += instance.OnGetASecondWeapon;
                @GetASecondWeapon.performed += instance.OnGetASecondWeapon;
                @GetASecondWeapon.canceled += instance.OnGetASecondWeapon;
                @GetAFirstWeapon.started += instance.OnGetAFirstWeapon;
                @GetAFirstWeapon.performed += instance.OnGetAFirstWeapon;
                @GetAFirstWeapon.canceled += instance.OnGetAFirstWeapon;
                @Shot.started += instance.OnShot;
                @Shot.performed += instance.OnShot;
                @Shot.canceled += instance.OnShot;
                @Reload.started += instance.OnReload;
                @Reload.performed += instance.OnReload;
                @Reload.canceled += instance.OnReload;
                @TakeAim.started += instance.OnTakeAim;
                @TakeAim.performed += instance.OnTakeAim;
                @TakeAim.canceled += instance.OnTakeAim;
            }

            private void UnregisterCallbacks(IGunActions instance)
            {
                @GetTheNinthWeapon.started -= instance.OnGetTheNinthWeapon;
                @GetTheNinthWeapon.performed -= instance.OnGetTheNinthWeapon;
                @GetTheNinthWeapon.canceled -= instance.OnGetTheNinthWeapon;
                @GetTheEghthWeapon.started -= instance.OnGetTheEghthWeapon;
                @GetTheEghthWeapon.performed -= instance.OnGetTheEghthWeapon;
                @GetTheEghthWeapon.canceled -= instance.OnGetTheEghthWeapon;
                @GetTheSeventhWeapon.started -= instance.OnGetTheSeventhWeapon;
                @GetTheSeventhWeapon.performed -= instance.OnGetTheSeventhWeapon;
                @GetTheSeventhWeapon.canceled -= instance.OnGetTheSeventhWeapon;
                @GetTheSixthWeapon.started -= instance.OnGetTheSixthWeapon;
                @GetTheSixthWeapon.performed -= instance.OnGetTheSixthWeapon;
                @GetTheSixthWeapon.canceled -= instance.OnGetTheSixthWeapon;
                @GetTheFifthWeapon.started -= instance.OnGetTheFifthWeapon;
                @GetTheFifthWeapon.performed -= instance.OnGetTheFifthWeapon;
                @GetTheFifthWeapon.canceled -= instance.OnGetTheFifthWeapon;
                @GetTheFourthWeapon.started -= instance.OnGetTheFourthWeapon;
                @GetTheFourthWeapon.performed -= instance.OnGetTheFourthWeapon;
                @GetTheFourthWeapon.canceled -= instance.OnGetTheFourthWeapon;
                @GetTheThirdWeapon.started -= instance.OnGetTheThirdWeapon;
                @GetTheThirdWeapon.performed -= instance.OnGetTheThirdWeapon;
                @GetTheThirdWeapon.canceled -= instance.OnGetTheThirdWeapon;
                @GetASecondWeapon.started -= instance.OnGetASecondWeapon;
                @GetASecondWeapon.performed -= instance.OnGetASecondWeapon;
                @GetASecondWeapon.canceled -= instance.OnGetASecondWeapon;
                @GetAFirstWeapon.started -= instance.OnGetAFirstWeapon;
                @GetAFirstWeapon.performed -= instance.OnGetAFirstWeapon;
                @GetAFirstWeapon.canceled -= instance.OnGetAFirstWeapon;
                @Shot.started -= instance.OnShot;
                @Shot.performed -= instance.OnShot;
                @Shot.canceled -= instance.OnShot;
                @Reload.started -= instance.OnReload;
                @Reload.performed -= instance.OnReload;
                @Reload.canceled -= instance.OnReload;
                @TakeAim.started -= instance.OnTakeAim;
                @TakeAim.performed -= instance.OnTakeAim;
                @TakeAim.canceled -= instance.OnTakeAim;
            }

            public void RemoveCallbacks(IGunActions instance)
            {
                if (m_Wrapper.m_GunActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IGunActions instance)
            {
                foreach (var item in m_Wrapper.m_GunActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_GunActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public GunActions @Gun => new GunActions(this);
        public interface IUserActionActions
        {
            void OnStopPlaying(InputAction.CallbackContext context);
            void OnAction(InputAction.CallbackContext context);
            void OnOpenInventary(InputAction.CallbackContext context);
        }
        public interface IMovementsActions
        {
            void OnMove(InputAction.CallbackContext context);
            void OnRotate(InputAction.CallbackContext context);
            void OnJumpe(InputAction.CallbackContext context);
            void OnSitDown(InputAction.CallbackContext context);
            void OnAccalerate(InputAction.CallbackContext context);
        }
        public interface IGunActions
        {
            void OnGetTheNinthWeapon(InputAction.CallbackContext context);
            void OnGetTheEghthWeapon(InputAction.CallbackContext context);
            void OnGetTheSeventhWeapon(InputAction.CallbackContext context);
            void OnGetTheSixthWeapon(InputAction.CallbackContext context);
            void OnGetTheFifthWeapon(InputAction.CallbackContext context);
            void OnGetTheFourthWeapon(InputAction.CallbackContext context);
            void OnGetTheThirdWeapon(InputAction.CallbackContext context);
            void OnGetASecondWeapon(InputAction.CallbackContext context);
            void OnGetAFirstWeapon(InputAction.CallbackContext context);
            void OnShot(InputAction.CallbackContext context);
            void OnReload(InputAction.CallbackContext context);
            void OnTakeAim(InputAction.CallbackContext context);
        }
    }
}
